spring:
  application:
    name: aipgvectordemo
  datasource:
    url: jdbc:postgresql://localhost:5432/sbdocs
    username: admin
    password: password
  ai:
    openai:
      api-key: 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
      chat:
        options:
          model: gpt-4
  vectorstore:
    pgvector:
    index-type: HNSW
    distance-type: COSINE_DISTANCE
    dimension: 1536
  docker:
    compose:
      lifecycle-management: start_only
#  main:
#    banner-mode: off
#logging:
#  level:
#    root: off
